# -*- coding: utf-8 -*-
"""Principal Component Analysis from scratch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eLtvBtKNxZTr_WWmsNXd6_0xKl5TteMD
"""

# Commented out IPython magic to ensure Python compatibility.
# Libraries
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
# %matplotlib inline

# The Data
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

cancer.keys()
df = pd.DataFrame(cancer['data'],columns=cancer['feature_names'])
df.head()

# We instantiate a PCA object,
# find the principal components using the fit method,
# then apply the rotation and dimensionality reduction by calling transform().
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(df)
scaled_data = scaler.transform(df)

# Create 2 PCA Object
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca.fit(scaled_data)
x_pca = pca.transform(scaled_data)

scaled_data.shape

x_pca.shape

# access values and vectors
pca.components_

pca.explained_variance_